name: mm-docs
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v3
      - run: ./Invoke-Build.ps1 Build
      - run: ./Invoke-Build.ps1 Run, ExportPdf, Stop
      - run: Write-Host ${{env.VERSION}}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
            name: docs
            path: "./docs/pdf/docs.pdf"
    env:
      VERSION: '1.2.3'
      MM_DOCS_URL_PREFIX: 'http://localhost:8000'