name: mm-docs
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v3
      - run: ./Invoke-Build.ps1 Build
      - run: ./Invoke-Build.ps1 Run, ExportPdf, Stop
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
            name: pdf
            path: ./source/pdf/docs.pdf
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
            name: site
            path: ./source/site
    env:
      VERSION: '1.2.3'
      MM_DOCS_URL_PREFIX: http://localhost:8000