name: mm-docs
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v3
      - run: ./Invoke-Build.ps1 Build
      - run: Write-Host "${VERSION}"
    env:
      VERSION: '1.2.3'
      MM_DOCS_URL_PREFIX: 'http://localhost:8000'